# Generated by Django 4.0.4 on 2022-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('category', models.CharField(choices=[('Django', 'Django'), ('React', 'React'), ('Agile', 'Agile'), ('Html', 'Html'), ('Css', 'Css'), ('Bootstrap', 'Bootstrap'), ('Github', 'Github'), ('Mui', 'Mui')], max_length=9)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Publish', 'Publish'), ('Private', 'Private')], default='Draft', max_length=7)),
            ],
        ),
    ]
